apiVersion: v1
kind: Service
metadata:
  name: balance-service
spec:
  selector:
    app: balance-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 31080
  type: NodePort
