# storage.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: auth-db
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: '/mnt/data/auth-db'
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auth-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
