apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - storage.yaml
  - config.yaml
  - service.yaml
  - statefulset.yaml

commonLabels:
  app: transaction-db
  environment: production
