apiVersion: v1
kind: Service
metadata:
  name: transaction-db
  labels:
    app: transaction-db
spec:
  clusterIP: None
  selector:
    app: transaction-db
  ports:
    - port: 27017
      targetPort: 27017
