apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: transaction-db
  labels:
    app: transaction-db
spec:
  serviceName: transaction-db-service
  replicas: 3
  selector:
    matchLabels:
      app: transaction-db
  template:
    metadata:
      labels:
        app: transaction-db
    spec:
      initContainers:
        - name: init-replicaset
          image: mongo:8.0
          command: ["/bin/bash"]
          args: ["/config/init.sh"]
          volumeMounts:
            - name: config
              mountPath: /config
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_USER
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_PASSWORD
      containers:
        - name: transaction-db
          image: mongo:8.0
          command:
            - "mongod"
            - "--bind_ip_all"
            - "--replSet"
            - "rs0"
          ports:
            - containerPort: 27017
              name: mongodb
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_USER
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_PASSWORD
          volumeMounts:
            - name: transaction-db-data
              mountPath: /data/db
          livenessProbe:
            exec:
              command:
                - mongosh
                - --eval
                - "db.runCommand('ping').ok"
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            exec:
              command:
                - mongosh
                - --eval
                - "db.runCommand('ping').ok"
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
      volumes:
        - name: config
          configMap:
            name: transaction-db-init
            defaultMode: 0755
        - name: transaction-db-data
          persistentVolumeClaim:
            claimName: transaction-db
