apiVersion: apps/v1
kind: Deployment
metadata:
  name: trading-bot
spec:
  selector:
    matchLabels:
      app: trading-bot
  replicas: 3
  template:
    metadata:
      labels:
        app: trading-bot
    spec:
      containers:
        - name: trading-bot
          image: boobit-ncr.kr.ncr.ntruss.com/trading-bot:latest
          env:
            - name: OPTIONS
              value: "--count=-1"
