apiVersion: v1
kind: ConfigMap
metadata:
  name: transaction-db-config
data:
  init.js: |
    db = db.getSiblingDB('boobit');
    db.createUser({
      user: process.env.MONGO_INITDB_ROOT_USERNAME,
      pwd: process.env.MONGO_INITDB_ROOT_PASSWORD,
      roles: [
        { role: "dbAdmin", db: "boobit" },
        { role: "readWrite", db: "boobit" }
      ]
    });
  mongod.conf: |
    storage:
      dbPath: /data/db
    net:
      bindIp: 0.0.0.0
