apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: transaction-db
spec:
  serviceName: transaction-db
  replicas: 1
  selector:
    matchLabels:
      app: transaction-db
  template:
    metadata:
      labels:
        app: transaction-db
    spec:
      containers:
        - name: transaction-db
          image: mongo:8.0
          resources:
            requests:
              cpu: '500m'
              memory: '1Gi'
            limits:
              cpu: '500m'
              memory: '1Gi'
          args: ['--config=/config/mongod.conf']
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_USER
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_PASSWORD
          volumeMounts:
            - name: transaction-db-storage
              mountPath: /data/db
            - name: transaction-db-config
              mountPath: /config/mongod.conf
              subPath: mongod.conf
            - name: transaction-db-config
              mountPath: /docker-entrypoint-initdb.d/init.js
              subPath: init.js
      volumes:
        - name: transaction-db-storage
          persistentVolumeClaim:
            claimName: transaction-db
        - name: transaction-db-config
          configMap:
            name: transaction-db-config
