apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-server
  labels:
    app: static-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: static-server
  template:
    metadata:
      labels:
        app: static-server
    spec:
      containers:
        - name: static-server
          image: boobit-ncr.kr.ncr.ntruss.com/static-server:latest #todo
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "125m"
              memory: "256Mi"
            limits:
              cpu: "125m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: static-server
spec:
  selector:
    app: static-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 32180
  type: NodePort
