apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: alb
  annotations:
    alb.ingress.kubernetes.io/ncloud-load-balancer-retain-public-ip-on-termination: "true" # 공인 IP 유지
    alb.ingress.kubernetes.io/public-ip-instance-no: "100522047"
    alb.ingress.kubernetes.io/healthcheck-path: /health
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /ws
            pathType: Prefix
            backend:
              service:
                name: transaction-service
                port:
                  number: 80
          - path: /api/auth
            pathType: Prefix
            backend:
              service:
                name: auth-service
                port:
                  number: 80
          - path: /api/users
            pathType: Prefix
            backend:
              service:
                name: balance-service
                port:
                  number: 80
          - path: /api/orders
            pathType: Prefix
            backend:
              service:
                name: transaction-service
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: static-server
                port:
                  number: 80
