apiVersion: apps/v1
kind: Deployment
metadata:
  name: interval-service
  labels:
    app: interval-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: interval-service
  template:
    metadata:
      labels:
        app: interval-service
    spec:
      containers:
        - name: interval-service
          image: boobit-ncr.kr.ncr.ntruss.com/interval-service:latest #todo
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          env:
            - name: DATABASE_URL
              value: "mongodb://$(DB_USER):$(DB_PASSWORD)@$(DB_HOST):27017/$(DB_SCHEMA)?replicaSet=rs0"
          envFrom:
            - configMapRef:
                name: interval-service-config
            - secretRef:
                name: db-credentials
