apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: auth-db
spec:
  serviceName: auth-db
  replicas: 1
  selector:
    matchLabels:
      app: auth-db
      type: database
  template:
    metadata:
      labels:
        app: auth-db
        type: database
    spec:
      containers:
        - name: auth-db
          image: mysql:8.0.22
          resources:
            requests:
              cpu: '500m'
              memory: '1Gi'
            limits:
              cpu: '500m'
              memory: '1Gi'
          args:
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
          ports:
            - containerPort: 3306
              name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: $(DB_ROOT_PASSWORD)
            - name: MYSQL_USER
              value: $(DB_USER)
            - name: MYSQL_PASSWORD
              value: $(DB_PASSWORD)
            - name: MYSQL_DATABASE
              value: $(DB_SCHEMA)
          envFrom:
            - secretRef:
                name: db-credentials
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
            - name: mysql-init-script
              mountPath: /docker-entrypoint-initdb.d
          livenessProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - -h
                - localhost
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: auth-db
        - name: mysql-init-script
          configMap:
            name: mysql-init-script
