apiVersion: apps/v1
kind: Deployment
metadata:
  name: balance-service
  labels:
    app: balance-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: balance-service
  template:
    metadata:
      labels:
        app: balance-service
    spec:
      containers:
        - name: balance-service
          image: boobit-ncr.kr.ncr.ntruss.com/balance-service:latest #todo
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          env:
            - name: DATABASE_URL
              value: "mysql://$(DB_USER):$(DB_PASSWORD)@$(DB_HOST):3306/$(DB_SCHEMA)"
          envFrom:
            - configMapRef:
                name: balance-service-config
            - secretRef:
                name: db-credentials
