# Build stage
FROM node:20-alpine AS builder

WORKDIR /app/view

# Copy only necessary files for this service
COPY view ./

# Install and build
RUN npm ci
RUN npm run build

# Production stage
FROM node:20-alpine

WORKDIR /app

# Copy package files and install dependencies
COPY static ./

RUN npm ci --only=production
COPY --from=builder /app/view/dist ./public

# Expose port
EXPOSE 8080

# Run application
CMD ["node", "app.js"]

