# Build stage
FROM node:20-alpine AS builder

WORKDIR /app

# Copy only necessary files for this service
COPY bot ./

# Install and build
RUN npm ci
RUN npm run build

# Production stage
FROM node:20-alpine

WORKDIR /app
COPY --from=builder /app ./

# Run application
CMD node dist/index.js ${OPTIONS}

