version: '3.8'

services:
  db:
    image: mysql:8.0.22
    container_name: mysql-server
    ports:
      - '${MYSQL_PORT}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./data:/var/lib/mysql
      - ./docker_init/mysql_init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      timeout: 5s
      retries: 5

  balance:
    container_name: balance-server
    build:
      context: .
      dockerfile: ./apps/balance/DockerFile
      args:
        DATABASE_URL: mysql://boobit:Boobit123@mysql-server:3306/boobit
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: mysql://boobit:Boobit123@mysql-server:3306/boobit
    depends_on:
      db:
        condition: service_healthy
    restart: always
