apiVersion: v1
kind: Service
metadata:
  name: transaction-service
spec:
  type: NodePort
  selector:
    app: transaction-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 32080
