name: Webhook Hello World

# repository_dispatch 이벤트로 트리거
on:
  repository_dispatch:
    types: [webhook-trigger]

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      # webhook으로 전달받은 데이터 출력
      - name: Print webhook payload
        run: |
          echo "Hello World!"
          echo "Webhook data received:"
          echo "Event Type: ${{ github.event.action }}"
          echo "Client Payload: ${{ toJSON(github.event.client_payload) }}"
